add methods for custom transport configuration
BiagioFesta/wtransport pull request #199
Opened 2024-08-11 07:34 UTC by mm88ggg

## Description

This pull request introduces two new methods to the `ServerConfigBuilder`:

1. **`with_custom_transport`**: Allows configuration of a server with a custom transport setup while using a default TLS configuration generated from an `Identity`. This method provides flexibility for users who need to customize transport settings without manually configuring TLS.

2. **`with_custom_tls_and_transport`**: Enables full customization of both TLS and transport settings. Users can pass a preconfigured `TlsServerConfig` and a custom `TransportConfig` to fine-tune both layers of the server configuration. This is particularly useful for advanced scenarios where specific TLS and transport requirements are necessary.

### Documentation and Examples

Both methods come with comprehensive documentation and usage examples to help users understand how to implement and use these configurations effectively.

### Motivation

While attempting to modify the `datagram_send_buffer_size` in `TransportConfig`, I noticed that even though there is a `pub fn quic_connection_mut(&mut self) -> &mut quinn::Connection` method, the `TransportConfig` is encapsulated within an `Arc`, which does not provide internal mutability through locking. As a result, even with a mutable reference, it is impossible to change its member variables directly. This limitation highlighted the need for additional methods to allow full customization of both TLS and transport configurations. These new methods are particularly useful for users who need to modify the `TransportConfig` or similar settings.

2024-08-12 21:08 UTC, BiagioFesta requested changes

2024-08-12 21:08 UTC, BiagioFesta commented on wtransport/src/config.rs
> +    pub fn with_custom_transport(
Please put this behind `quinn` feature, like:

```rust
    #[cfg(feature = "quinn")]
    #[cfg_attr(docsrs, doc(cfg(feature = "quinn")))]
```

as this requires access to third party dep

2024-08-12 21:08 UTC, BiagioFesta commented on wtransport/src/config.rs
> +        transport_config: TransportConfig,
As made for `rustls`. Please re-export this third party symbol. That is:

at the begging of the module, appending existing type aliases
```
/// Alias of [`crate::quinn::TransportConfig`].
pub type QuicTransportConfig = crate::quinn::TransportConfig;
```

2024-08-12 21:08 UTC, BiagioFesta commented on wtransport/src/config.rs
> +    /// This method is useful for scenarios where you need to customize the transport settings
I think we can add a note in the documentation.

```
**See**:  [with_identity] ...
```

mentioning that this method is equivalent to the simpler `with_identity`, but it just allows adding the QUIC transport configuration.

This help the user to understand this behave exactly like `with_identity`.

---

Same comment for the `with_custom_tls` below

2024-08-12 21:09 UTC, BiagioFesta commented
Thank you for the feedback and the improvement.

I agree with you, and I think we should go ahead with your proposal change. We want to provide an API to setup QUIC transport configuration.

I've just added a few comment to better integrate your code with the ergonomic of the existing code.

Thanks

2024-08-13 06:36 UTC, mm88ggg commented
> Thank you for the feedback and the improvement.
> 
> I agree with you, and I think we should go ahead with your proposal change. We want to provide an API to setup QUIC transport configuration.
> 
> I've just added a few comment to better integrate your code with the ergonomic of the existing code.
> 
> Thanks

Thank you for the feedback. I have committed the modified version. Instead of using pub type QuicTransportConfig = crate::quinn::TransportConfig;, I opted for use quinn::TransportConfig as QuicTransportConfig;. Since quinn is not a module within wtransport, I couldn't use crate:: to import it. Additionally, you are already using use quinn::ClientConfig as QuicClientConfig; and use quinn::ServerConfig as QuicServerConfig;, so I followed the same approach.

Please review the changes, and if you encounter any issues, feel free to reach out.

2024-08-13 09:34 UTC, BiagioFesta commented
> [...] Since quinn is not a module within wtransport [...]

It is: https://github.com/BiagioFesta/wtransport/blob/master/wtransport/src/lib.rs#L146

(probably you don't see it because it's behind a feature flag).

2024-08-13 09:35 UTC, BiagioFesta requested changes
We should have `crate::quinn` (when `quinn` feature is enabled), so let's go with the `pub type ...` as mentioned before

2024-08-13 09:36 UTC, BiagioFesta requested changes
I think we squash into a single commit for this feature

2024-08-13 10:27 UTC, BiagioFesta approved these changes

2024-08-13 10:27 UTC, BiagioFesta commented
Thank you!

2024-08-13 10:59 UTC, merged