Exposing more methods on wtransport::Connection from underlying quinn::Connection object
BiagioFesta/wtransport pull request #26
Opened 2023-07-11 02:05 UTC by JustSomeDude301

#25

2023-07-11 16:56 UTC, BiagioFesta requested changes
Thanks for this.

LGTM, just a few nits on doc

2023-07-11 16:56 UTC, BiagioFesta commented on wtransport/src/connection.rs
> +    /// Compute the maximum size of datagrams that may be passed to [`send_datagram()`].
nit: Compute(s)*

2023-07-11 16:56 UTC, BiagioFesta commented on wtransport/src/connection.rs
> +    /// Current best estimate of this connection's latency (round-trip-time)
nit: full stop and the end of the sentence

2023-07-11 16:56 UTC, BiagioFesta commented on wtransport/src/connection.rs
> +    /// A stable identifier for this connection
nit: Full stop at the end of the line

2023-07-13 16:58 UTC, BiagioFesta commented
I rebased your PR and squashed in one single commit.

I merged the commit on `master`, but GitHub is not able to see the merge because I fix a nit. Can you try to rebase the branch on your fork?

2023-07-14 02:57 UTC, JustSomeDude301 commented
Rebased, please do not hesitate to let me know if you need me to do anything else in future issues. Thank you again for your suggestions on my connection map and for your work on this library. If you have a private channel (like a discord server) I'd be more than happy to share more about my use case

2023-07-14 13:15 UTC, merged

2023-07-14 15:01 UTC, BiagioFesta commented
I am not really into Discord, but I think it might be a good idea to start a project related chat-community.

https://wtransport.zulipchat.com